# Generated by Django 5.2.17 on 2026-09-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('roomtype_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='Room Type ID')),
                ('roomtype_name', models.CharField(max_length=30)),
                ('roomtype_description', models.TextField()),
                ('roomtype_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('roomtype_capacity', models.IntegerField()),
                ('roomtype_amenities', models.TextField(max_length=255)),
            ],
        ),
    ]
