# Generated by Django 5.2.17 on 2026-09-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('guest_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='Guest ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.TextField(max_length=50)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
